name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
    - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python_version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - uses: astral-sh/setup-uv@v5
        with:
          version: '0.6.16'
      - run: uv sync --python ${{ matrix.python_version }}
      - run: uv run pytest